name: Phood
favicon: null
layout_spectrum: 0.6723280751612037
typography_spectrum: 0.1253963892813772
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8128737471997738
  lightness: 0.012274333043023944
  saturation: 0.41687146900221705
  rhythmicContrast: 0.1715913221705705
purpose: []
